source "https://rubygems.org"

gem 'sqlite3'
gem 'sequel'
gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'database_cleaner'
gem 'guard-cucumber'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'capybara'
gem 'poltergeist'
gem 'selenium-webdriver'

